# Generated by Django 2.1.15 on 2022-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=50)),
                ('released', models.DateField(null=True)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.IntegerField()),
                ('imdbrating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdbvotes', models.IntegerField()),
                ('imdbid', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.DateField(null=True)),
                ('boxoffice', models.IntegerField()),
                ('production', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
